class Logo
  def initialize(rows, start)
    @rows = rows
    @start = start
  end

  def call
    array = []
    7.times.each do |t|
      array << [ @rows - t, @start + t..@start + t + 3 ]
    end
    5.times.each do |t|
      array << [ @rows - (5 - t), @start + (10 + t)..@start + (13 + t)]
    end
    array << [ @rows    ,  @start + 15..@start + 18]
    array << [ @rows    ,  @start + 8..@start +  11]
    array << [ @rows    ,  @start + 31..@start + 34]
    array << [ @rows    ,  @start + 19]
    array << [ @rows    ,  @start + 53..@start + 56]
    array << [ @rows - 1,  @start + 18..@start + 20]
    array << [ @rows - 1,  @start + 30..@start + 33]
    array << [ @rows - 1,  @start +  9..@start + 12]
    array << [ @rows - 1,  @start + 52..@start + 55]
    array << [ @rows - 10, @start + 18..@start + 24]
    array << [ @rows - 10, @start + 26..@start + 29]
    array << [ @rows - 10, @start + 43..@start + 46]
    array << [ @rows - 11, @start + 19..@start + 23]
    array << [ @rows - 11, @start + 27..@start + 30]
    array << [ @rows - 11, @start + 42..@start + 45]
    array << [ @rows - 12, @start + 20..@start + 22]
    array << [ @rows - 12, @start + 28..@start + 31]
    array << [ @rows - 12, @start + 41..@start + 44]
    array << [ @rows - 13, @start + 21]
    array << [ @rows - 13, @start + 29..@start + 32]
    array << [ @rows - 13, @start + 40..@start + 43]
    array << [ @rows - 14, @start + 30..@start + 33]
    array << [ @rows - 14, @start + 39..@start + 42]
    array << [ @rows - 15, @start + 31..@start + 34]
    array << [ @rows - 15, @start + 38..@start + 41]
    array << [ @rows - 16, @start + 32..@start + 35]
    array << [ @rows - 16, @start + 37..@start + 40]
    array << [ @rows - 17, @start + 33..@start + 39]
    array << [ @rows - 18, @start + 34..@start + 38]
    array << [ @rows - 19, @start + 35..@start + 37]
    array << [ @rows - 2, @start + 10..@start + 12]
    array << [ @rows - 2, @start + 18..@start + 21]
    array << [ @rows - 2, @start + 29..@start + 32]
    array << [ @rows - 2, @start + 51..@start + 54]
    array << [ @rows - 20, @start + 36]
    array << [ @rows - 3, @start + 11]
    array << [ @rows - 3, @start + 19..@start + 22]
    array << [ @rows - 3, @start + 28..@start + 31]
    array << [ @rows - 3, @start + 50..@start + 53]
    array << [ @rows - 4, @start + 15]
    array << [ @rows - 4, @start + 20..@start + 23]
    array << [ @rows - 4, @start + 27..@start + 30]
    array << [ @rows - 4, @start + 49..@start + 52]
    array << [ @rows - 5, @start + 14..@start + 16]
    array << [ @rows - 5, @start + 21..@start + 24]
    array << [ @rows - 5, @start + 26..@start + 29]
    array << [ @rows - 5, @start + 48..@start + 51]
    array << [ @rows - 6, @start + 10..@start + 12]
    array << [ @rows - 6, @start + 14..@start + 17]
    array << [ @rows - 6, @start + 22..@start + 24]
    array << [ @rows - 6, @start + 25..@start + 28]
    array << [ @rows - 6, @start + 47..@start + 50]
    array << [ @rows - 7, @start + 11]
    array << [ @rows - 7, @start + 15..@start + 18]
    array << [ @rows - 7, @start + 23]
    array << [ @rows - 7, @start + 24..@start + 27]
    array << [ @rows - 7, @start + 7..@start + 10 ]
    array << [ @rows - 7, @start + 46..@start + 49]
    array << [ @rows - 8, @start + 16..@start + 19]
    array << [ @rows - 8, @start + 23..@start + 26]
    array << [ @rows - 8, @start + 27 ]
    array << [ @rows - 8, @start + 8..@start + 10 ]
    array << [ @rows - 8, @start + 45..@start + 48]
    array << [ @rows - 9, @start + 17..@start + 20]
    array << [ @rows - 9, @start + 22..@start + 25]
    array << [ @rows - 9, @start + 26..@start + 28]
    array << [ @rows - 9, @start + 9 ]
    array << [ @rows - 9, @start + 44..@start + 47]

  end
end
